### ISSUE TITLE
Aktivieren des Ontologie-Browsers

### ISSUE THREAD

**Issue by shichikoromo** [KohlbacherLab/nse-mv-genomseq#1]
Die Anbindung an die Bioportal-API ist nicht möglich, wenn der REDCap-Server in einer geschützten Netzwerkzone ohne Kommunikationsmöglichkeiten ins Internet betrieben wird. Durch die Verarbeitung von Patientendaten ist ein solcher Betrieb empfehlenswert ggf. vorgeschrieben. Außerdem ist die verwendete ICD-10-Version (2024AA) in Deutschland nicht gültig (kein ICD-10-GM).

**Comment by cerhardt** [comment]
Hallo @shichikoromo,
die Netzwerkanbindung von REDCap wird vermutlich an jedem Standort anders gelöst sein. Ich kann dazu keine Annahmen treffen, würde aber eine funktionierende Anbindung an die Bioportal API als Basisfunktionalität von REDCap bezeichnen.
Zu ICD-10-GM: Sie haben Recht, über die Bioportal API erhält man nicht die deutsche Version von ICD-10, dies wurde dem ZSE Tübingen auch kommuniziert. Inwieweit das ein Problem ist (ausser der Suche nach englischen Diagnosen), kann ich nicht sagen. Kennen Sie eine frei verfügbare API für ICD-10-GM?

**Comment by DannyAmmon** [comment]
Das sollte unbedingt geklärt werden – üblicherweise schließen sich in deutschen Krankenhäusern Verarbeitung von Patientendaten und Zugriffe ins Internet grundsätzlich aus. Terminologien sollten über einen Dienst im lokalen Netzwerk abgefragt werden, dafür gibt es keinen Grund für Zugriffe nach außen. Künftig werden Standorte die [FHIR-konformen Kodiersysteme des BfArM](https://terminologien.bfarm.de) lokal synchronisieren, dazu zählen auch die in Deutschland verpflichtend zu verwendenden Versionen der ICD-10-GM.

**Comment by cerhardt** [comment]
s. Kommentar oben

**Comment by cerhardt** [comment]
@shichikoromo @DannyAmmon Die Vorlage verwendet jetzt ICD-10-GM (2025) und hat eine integrierte Suche nach den Kreisschlüsseln. Verwendet wird dafür das Modul "Simple Ontology Module".
