### ISSUE TITLE
Fragebogen als Survey

### ISSUE THREAD

**Issue by shichikoromo** [KohlbacherLab/nse-mv-genomseq#2]
Bei der Vorstellung des Fragebogens für unsere klinischen Kollegen kam die Rückmeldung, dass die Nutzung der REDCap-Oberfläche zu kompliziert sei.
Ist es möglich, das Ausfüllen des Fragebogens als Survey umzusetzen?
Dabei sollte auch die Nutzung der Felder mit External-Module-Aufrufen möglich sein (geht zur Zeit leider nicht).

**Comment by cerhardt** [comment]
Das Ausfüllen der Fragebögen als Survey ist nicht vorgesehen / geplant. Die Vorlage kann natürlich am Standort durch Aktivieren der Fragebögen als Umfragen etc. so verwendet werden, wird aber weder empfohlen noch unterstützt.

**Comment by cerhardt** [comment]
Das Ausfüllen der Fragebögen als Survey ist nicht vorgesehen / geplant. Die Vorlage kann natürlich am Standort durch Aktivieren der Fragebögen als Umfragen etc. so verwendet werden, wird aber weder empfohlen noch unterstützt.

**Comment by cerhardt** [comment]
Das Ausfüllen der Fragebögen als Survey ist nicht vorgesehen / geplant. Die Vorlage kann natürlich am Standort durch Aktivieren der Fragebögen als Umfragen etc. so verwendet werden, wird aber weder empfohlen noch unterstützt.
